MAO-A:
  TargetID: 532
  nr_layers: 3
  weight_decay: 0.01
  hidden_sizes: 14
  dropout: 0
  learning_rate: 0.1
  evaluate_testset: false
  save_model: false


hERG:
  TargetID: 1133
  nr_layers: 1
  weight_decay: 0.001
  hidden_sizes: 14
  dropout: 0
  learning_rate: 0.1
  evaluate_testset: false
  save_model: false


CYP:
  TargetID: 1908
  nr_layers: 1
  weight_decay: 0.01
  hidden_sizes: 30
  dropout: 0
  learning_rate: 0.1
  evaluate_testset: false
  save_model: false
