MAO-A:
  TargetID: 532
  nr_layers: 1
  weight_decay: 0.01
  hidden_sizes: 18
  dropout: 0
  nr_chains: 5
  step_size: 0.001
  nr_samples: 150
  L: 150
  tau_out: 1.0
  save_model: false
  evaluate_testset: false

hERG:
  TargetID: 1133
  nr_layers: 1
  weight_decay: 0.001
  hidden_sizes: 14
  dropout: 0
  nr_chains: 5
  step_size: 0.001
  nr_samples: 150
  L: 150
  tau_out: 1.0
  save_model: false
  evaluate_testset: false

CYP:
  TargetID: 1908
  nr_layers: 1
  weight_decay: 0.01
  hidden_sizes: 30
  dropout: 0
  nr_chains: 2
  step_size: 0.001
  nr_samples: 150
  L: 150
  tau_out: 1.0
  save_model: false
  evaluate_testset: false