#!/bin/bash

#SBATCH --account=lp_biolearning 
#SBATCH --name=Sweep_1133 
#SBATCH --clusters=genius
#SBATCH --partition=gpu_p100
#SBATCH --time=24:00:00 
#SBATCH --nodes=1
#SBATCH --gpus-per-node=1
#SBATCH --mem=6G
#SBATCH --output=logs/sweep_1133.log

source activate SparseChem

#wandb sweep /home/user/leuven/356/vsc35684/DATA/AIDD/AIDDProject/SingleTask_sweeps/sweep_baseline.yaml
wandb agent rosa/uq-hmc/gakne0gu
